### ISSUE TITLE
UpSampling2dLayer+Conv2d or DeConv2d?

### ISSUE THREAD

**Issue by LynnHo** [yzwxx/vae-celebA#1]
Thanks for the good code!
I have two questions:
1. Is UpSampling2dLayer+Conv2d better than DeConv2d? How about the results of DeConv2d?
2. How about the results of using the original VAE loss without perceptual loss?

**Comment by yzwxx** [comment]
1.It has been pointed out that UpSampling2dLayer+Conv2d prevents the checkerboard artifacts, which you may come across using DeConv2d. Check this for more details. (https://distill.pub/2016/deconv-checkerboard). I have done some research on GAN models and it works well using DeConv2d  for upsampling.
2. Using original mean square error gives images of human faces that are blurrier rather the results I put in this repo.
Hope the answer helps!
